/**
 * Initial component descriptions for the UAI component tree.
 *
 * These are the architectural components registered at startup.
 * Each provides a describe() implementation returning ComponentDescription.
 * Workstreams 1B-1D will add their own components.
 */

import type { ComponentDescription } from '../../../architecture/contracts';
import { ComponentRegistry, type DescribableComponent } from './component-registry';

// ─── Component Descriptions ───────────────────────────────────────────────

const SESSION_NAVIGATOR: ComponentDescription = {
  schema_version: 1,
  id: 'session_navigator',
  path: 'app.session_navigator',
  name: 'Session Navigator',
  description: 'Left panel showing sessions, briefs, teams, and projects in tabbed lists with filtering, sorting, and multi-select.',
  parent: 'app',
  children: [],
  state: {
    activeTab: {
      schema: { type: 'string', enum: ['sessions', 'briefs', 'teams', 'projects'] },
      description: 'Currently active navigator tab',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 'sessions',
    },
    filter: {
      schema: { type: 'object' },
      description: 'Active filter criteria (status, platform, search text)',
      readable: true,
      writable: true,
      write_mechanism: 'local',
    },
    sort: {
      schema: { type: 'object', properties: { field: { type: 'string' }, direction: { type: 'string' } } },
      description: 'Current sort configuration',
      readable: true,
      writable: true,
      write_mechanism: 'local',
    },
  },
  commands: {
    'session.update': {
      description: 'Update session fields (e.g., rename)',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' }, patch: { type: 'object' } } },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: ['sessions'],
      side_effects: ['Persists to SQLite via session_store.py'],
      preconditions: ['Session exists'],
      postconditions: ['Session fields updated'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'UPDATE_FAILED'],
    },
    'session.create': {
      description: 'Create a new session (draft + launch)',
      parameters: { type: 'object', properties: { platform: { type: 'string' } } },
      returns: { type: 'object', properties: { trackingId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:create' }],
      affected_stores: ['sessions'],
      side_effects: ['Creates SQLite row', 'Launches terminal session via ai_launcher'],
      preconditions: [],
      postconditions: ['Draft session exists in store', 'Launcher invoked'],
      idempotent: false,
      async: true,
      latency: 'slow',
      error_codes: ['CREATE_FAILED'],
    },
  },
  actions: {
    selectSession: {
      description: 'Click a session card to select/focus it',
      trigger_command: 'workspace.tabs.open',
      context_description: 'session tracking_id from card',
    },
    renameSession: {
      description: 'Rename a session via context menu',
      trigger_command: 'session.update',
      context_description: 'session tracking_id + new display_name',
    },
  },
  events: {
    'session:selected': {
      description: 'Fires when user selects a session card',
      data_schema: { type: 'object', properties: { trackingId: { type: 'string' } } },
      trigger: 'User clicks session card',
    },
  },
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Currently focused entity', required: false },
    { key: 'selection', type: 'Set<string>', description: 'Multi-selected entity IDs', required: false },
  ],
};

const WORKSPACE: ComponentDescription = {
  schema_version: 1,
  id: 'workspace',
  path: 'app.workspace',
  name: 'Workspace',
  description: 'Center panel with tabbed entity views. Tab bar selects the active entity. Each tab dispatches to an entity-specific view via TabContentPane.',
  parent: 'app',
  children: ['entity_view'],
  state: {
    tabs: {
      schema: { type: 'array', items: { type: 'object' } },
      description: 'Open tabs with session references',
      readable: true,
      writable: true,
      write_mechanism: 'command',
    },
    activeTabId: {
      schema: { type: 'string', nullable: true },
      description: 'Currently active tab',
      readable: true,
      writable: true,
      write_mechanism: 'command',
    },
  },
  commands: {
    'workspace.tabs.open': {
      description: 'Open or activate a tab for an entity',
      parameters: { type: 'object', properties: { type: { type: 'string' }, targetId: { type: 'string' }, label: { type: 'string' }, deepLinkId: { type: 'string' } }, required: ['type', 'targetId', 'label'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, tabId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: [],
      postconditions: ['Tab exists and is active'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: [],
    },
    'workspace.tabs.close': {
      description: 'Close a tab',
      parameters: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: ['Tab exists'],
      postconditions: ['Tab removed from tab list'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: ['NOT_FOUND'],
    },
    'workspace.tabs.activate': {
      description: 'Switch to a tab',
      parameters: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: ['Tab exists'],
      postconditions: ['Tab is active'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: ['NOT_FOUND'],
    },
    'workspace.tabs.update': {
      description: 'Update tab properties (label, etc.)',
      parameters: { type: 'object', properties: { tabId: { type: 'string' }, patch: { type: 'object' } }, required: ['tabId', 'patch'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: ['Tab exists'],
      postconditions: ['Tab properties updated'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: ['NOT_FOUND'],
    },
  },
  actions: {
    openTab: {
      description: 'Open a session in a new tab',
      trigger_command: 'workspace.tabs.open',
      context_description: 'session tracking_id',
    },
    closeTab: {
      description: 'Close a tab',
      trigger_command: 'workspace.tabs.close',
      context_description: 'tab ID',
      shortcut: 'Cmd+W',
    },
    switchTab: {
      description: 'Switch to a different tab',
      trigger_command: 'workspace.tabs.activate',
      context_description: 'tab ID or index',
      shortcut: 'Cmd+1-9',
    },
  },
  events: {
    'tab:opened': {
      description: 'Fires when a new tab is opened',
      data_schema: { type: 'object', properties: { tabId: { type: 'string' }, sessionId: { type: 'string' } } },
      trigger: 'User opens a session tab',
    },
    'tab:closed': {
      description: 'Fires when a tab is closed',
      data_schema: { type: 'object', properties: { tabId: { type: 'string' } } },
      trigger: 'User closes a tab',
    },
  },
  context: [],
};

const SESSION_PANE: ComponentDescription = {
  schema_version: 1,
  id: 'session_pane',
  path: 'app.workspace.entity_view.session_pane',
  name: 'Session Pane',
  description: 'Terminal view for a single session with header, xterm.js terminal, Memorex overlay toggle, and selection overlay.',
  parent: 'entity_view',
  children: [],
  state: {
    memorexEnabled: {
      schema: { type: 'boolean' },
      description: 'Whether Memorex transcript overlay is visible',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: false,
    },
    splitRatio: {
      schema: { type: 'number', minimum: 0.15, maximum: 0.85 },
      description: 'Memorex/terminal split ratio',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 0.5,
    },
  },
  commands: {
    'session.stop': {
      description: 'Stop the session terminal',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' }, force: { type: 'boolean' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'requires_confirmation',
      required_capabilities: [{ capability: 'terminal:kill' }],
      affected_stores: ['sessions'],
      side_effects: ['Sends SIGTERM/SIGKILL to terminal process'],
      preconditions: ['Session exists', 'Session is running'],
      postconditions: ['Session terminal stopped'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'ALREADY_STOPPED'],
    },
    'session.block': {
      description: 'Block a session from receiving prompts from anyone but PianoMan (held prompts release on unblock). Omit turns+until for an indefinite block.',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' }, turns: { type: 'number' }, until: { type: 'string' }, reason: { type: 'string' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: ['sessions'],
      side_effects: ['Writes a prompt-block lock; other sessions’ prompts to the target are held'],
      preconditions: ['Session exists'],
      postconditions: ['Session is prompt-blocked'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['BLOCK_FAILED'],
    },
    'session.unblock': {
      description: 'Lift a session’s prompt-block and release any held prompts.',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: ['sessions'],
      side_effects: ['Removes the prompt-block lock; held prompts are delivered'],
      preconditions: ['Session exists'],
      postconditions: ['Session is not prompt-blocked'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['UNBLOCK_FAILED'],
    },
    'session.resume': {
      description: 'Resume a stopped session',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: ['sessions'],
      side_effects: ['Relaunches terminal session via ai_launcher'],
      preconditions: ['Session exists', 'Session is stopped'],
      postconditions: ['Session terminal running'],
      idempotent: true,
      async: true,
      latency: 'slow',
      error_codes: ['NOT_FOUND', 'ALREADY_RUNNING', 'RESUME_FAILED'],
    },
  },
  actions: {
    toggleMemorex: {
      description: 'Toggle Memorex transcript overlay',
      trigger_command: 'internal',
      context_description: 'Local state toggle for memorexEnabled',
    },
  },
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Session being displayed', required: true },
  ],
};

const CONTEXT_PANEL: ComponentDescription = {
  schema_version: 1,
  id: 'context_panel',
  path: 'app.workspace.entity_view.context_panel',
  name: 'Context Panel',
  description: 'Right collapsible detail panel owned by the active entity view. Content varies by entity type. Session entities show: Details, Context/Docs, MCP, Messages, Prompts.',
  parent: 'entity_view',
  children: [],
  state: {
    open: {
      schema: { type: 'boolean' },
      description: 'Whether the panel is open',
      readable: true,
      writable: true,
      write_mechanism: 'command',
      default_value: false,
    },
    activeTab: {
      schema: { type: 'string', enum: ['details', 'digests', 'docs', 'messages', 'prompts'] },
      description: 'Active detail tab',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 'details',
    },
    width: {
      schema: { type: 'number' },
      description: 'Panel width in pixels',
      readable: true,
      writable: true,
      write_mechanism: 'command',
      default_value: 300,
    },
  },
  commands: {
    'app.state.update': {
      description: 'Toggle or resize the context panel',
      parameters: { type: 'object', properties: { patch: { type: 'object', properties: { contextPanelOpen: { type: 'boolean' }, contextPanelWidth: { type: 'number' } } } }, required: ['patch'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: [],
      postconditions: ['App state patched'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: [],
    },
    'tag.add': {
      description: 'Add a tag to the active session',
      parameters: { type: 'object', properties: { cardId: { type: 'string' }, tag: { type: 'string' } }, required: ['cardId', 'tag'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'tags:write' }],
      affected_stores: ['tags'],
      side_effects: ['Persists tag to SQLite'],
      preconditions: ['Entity exists'],
      postconditions: ['Tag associated with entity'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
    'tag.remove': {
      description: 'Remove a tag from the active session',
      parameters: { type: 'object', properties: { cardId: { type: 'string' }, tag: { type: 'string' } }, required: ['cardId', 'tag'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'tags:write' }],
      affected_stores: ['tags'],
      side_effects: ['Removes tag from SQLite'],
      preconditions: ['Entity exists', 'Tag exists on entity'],
      postconditions: ['Tag removed from entity'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
    'session.stop': {
      description: 'Stop session from details panel',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'requires_confirmation',
      required_capabilities: [{ capability: 'terminal:kill' }],
      affected_stores: ['sessions'],
      side_effects: ['Sends SIGTERM to terminal process'],
      preconditions: ['Session exists', 'Session is running'],
      postconditions: ['Session terminal stopped'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'ALREADY_STOPPED'],
    },
    'session.resume': {
      description: 'Resume session from details panel',
      parameters: { type: 'object', properties: { trackingId: { type: 'string' } }, required: ['trackingId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: ['sessions'],
      side_effects: ['Relaunches terminal session via ai_launcher'],
      preconditions: ['Session exists', 'Session is stopped'],
      postconditions: ['Session terminal running'],
      idempotent: true,
      async: true,
      latency: 'slow',
      error_codes: ['NOT_FOUND', 'ALREADY_RUNNING', 'RESUME_FAILED'],
    },
  },
  actions: {
    toggle: {
      description: 'Toggle panel open/closed',
      trigger_command: 'app.state.update',
      context_description: 'Patches contextPanelOpen in app state',
    },
  },
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Entity whose details are shown', required: false },
  ],
};

const BOTTOM_PANEL: ComponentDescription = {
  schema_version: 1,
  id: 'bottom_panel',
  path: 'app.bottom_panel',
  name: 'Bottom Panel',
  description: 'Bottom drawer with tabs: Related Entities, Session Log, App Log, System Monitor.',
  parent: 'app',
  children: [],
  state: {
    open: {
      schema: { type: 'boolean' },
      description: 'Whether the panel is open',
      readable: true,
      writable: true,
      write_mechanism: 'command',
      default_value: false,
    },
    activeTab: {
      schema: { type: 'string', enum: ['related', 'logs', 'app_log', 'monitor'] },
      description: 'Active bottom panel tab',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 'related',
    },
    height: {
      schema: { type: 'number' },
      description: 'Panel height in pixels',
      readable: true,
      writable: true,
      write_mechanism: 'command',
      default_value: 200,
    },
  },
  commands: {
    'app.state.update': {
      description: 'Toggle the bottom panel open/closed',
      parameters: { type: 'object', properties: { patch: { type: 'object', properties: { bottomPanelOpen: { type: 'boolean' } } } }, required: ['patch'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: [],
      postconditions: ['App state patched'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: [],
    },
  },
  actions: {
    toggle: {
      description: 'Toggle panel open/closed',
      trigger_command: 'app.state.update',
      context_description: 'Patches bottomPanelOpen in app state',
    },
  },
  events: {},
  context: [],
};

const ENTITY_VIEW: ComponentDescription = {
  schema_version: 1,
  id: 'entity_view',
  path: 'app.workspace.entity_view',
  name: 'Entity View',
  description: 'Dispatches to type-specific entity views (session, project, team, folder, terminal, brief, transcript, search). Each entity view may compose its own detail panel.',
  parent: 'workspace',
  children: ['session_pane', 'context_panel'],
  state: {},
  commands: {
    'workspace.tabs.open': {
      description: 'Navigate to an entity from within a view',
      parameters: { type: 'object', properties: { type: { type: 'string' }, targetId: { type: 'string' }, label: { type: 'string' } }, required: ['type', 'targetId', 'label'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, tabId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: [],
      postconditions: ['Tab opened for target entity'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: [],
    },
    'folder.create': {
      description: 'Create a subfolder in folder view',
      parameters: { type: 'object', properties: { parentId: { type: 'string' }, name: { type: 'string' } }, required: ['parentId', 'name'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, folderId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists folder to SQLite'],
      preconditions: ['Parent folder exists'],
      postconditions: ['Subfolder created'],
      idempotent: false,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'CREATE_FAILED'],
    },
    'session.create': {
      description: 'Create a session from folder/project view',
      parameters: { type: 'object', properties: { platform: { type: 'string' }, projectDir: { type: 'string' }, roles: { type: 'array', items: { type: 'string' } } }, required: ['platform'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, trackingId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:create' }],
      affected_stores: ['sessions'],
      side_effects: ['Creates SQLite row', 'Launches terminal session via ai_launcher'],
      preconditions: [],
      postconditions: ['Draft session exists in store', 'Launcher invoked'],
      idempotent: false,
      async: true,
      latency: 'slow',
      error_codes: ['CREATE_FAILED'],
    },
  },
  actions: {},
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Entity being displayed', required: true },
  ],
};

const APP_ROOT: ComponentDescription = {
  schema_version: 1,
  id: 'app',
  path: 'app',
  name: 'UAI Application',
  description: 'Root component of the UAI application. Parent of all top-level panels.',
  parent: null as unknown as string,
  children: ['session_navigator', 'workspace', 'bottom_panel'],
  state: {},
  commands: {},
  actions: {},
  events: {},
  context: [],
};

// ─── Card/Container Components (Phase 2A) ───────────────────────────────

const CARD_LIST_VIEW: ComponentDescription = {
  schema_version: 1,
  id: 'card_list',
  path: 'app.session_navigator.card_list',
  name: 'Card List View',
  description: 'Generic sortable, filterable, multi-selectable card list. Renders any AnyCard type through CardRenderer discriminated union dispatch.',
  parent: 'session_navigator',
  children: [],
  state: {},
  commands: {
    'workspace.tabs.open': {
      description: 'Open a card entity in a new tab',
      parameters: { type: 'object', properties: { type: { type: 'string' }, targetId: { type: 'string' }, label: { type: 'string' } }, required: ['type', 'targetId', 'label'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, tabId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [],
      affected_stores: ['appState'],
      side_effects: [],
      preconditions: [],
      postconditions: ['Tab opened for card entity'],
      idempotent: true,
      async: false,
      latency: 'immediate',
      error_codes: [],
    },
    'folder.moveCard': {
      description: 'Move a card to a folder via drag-drop',
      parameters: { type: 'object', properties: { cardId: { type: 'string' }, folderId: { type: 'string' }, index: { type: 'number' } }, required: ['cardId', 'folderId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists card-folder association to SQLite'],
      preconditions: ['Card exists', 'Folder exists'],
      postconditions: ['Card filed in folder'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
  },
  actions: {
    click: { description: 'Select a card', trigger_command: 'internal', context_description: 'Local state: sets selected card entity_id' },
    select: { description: 'Multi-select a card (cmd/ctrl+click)', trigger_command: 'internal', context_description: 'Local state: toggles card in selection set' },
    contextMenu: { description: 'Show context menu for a card', trigger_command: 'internal', context_description: 'Local state: opens context menu at mouse position' },
  },
  events: {},
  context: [],
};

const CONTAINER_TREE_VIEW: ComponentDescription = {
  schema_version: 1,
  id: 'container_tree',
  path: 'app.session_navigator.container_tree',
  name: 'Container Tree View',
  description: 'Generic collapsible tree with container navigation. Works with any container type (folders, groups). Sub-containers as collapsible nodes, cards as leaves.',
  parent: 'session_navigator',
  children: ['card_list'],
  state: {
    collapsed: {
      schema: { type: 'object' },
      description: 'Set of collapsed container IDs',
      readable: true,
      writable: true,
      write_mechanism: 'local',
    },
  },
  commands: {
    'folder.create': {
      description: 'Create a subfolder',
      parameters: { type: 'object', properties: { parentId: { type: 'string' }, name: { type: 'string' } }, required: ['parentId', 'name'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' }, folderId: { type: 'string' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists folder to SQLite'],
      preconditions: ['Parent folder exists'],
      postconditions: ['Subfolder created'],
      idempotent: false,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'CREATE_FAILED'],
    },
    'folder.rename': {
      description: 'Rename a folder',
      parameters: { type: 'object', properties: { folderId: { type: 'string' }, name: { type: 'string' } }, required: ['folderId', 'name'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists rename to SQLite'],
      preconditions: ['Folder exists'],
      postconditions: ['Folder name updated'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
    'folder.delete': {
      description: 'Delete a folder',
      parameters: { type: 'object', properties: { folderId: { type: 'string' } }, required: ['folderId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'destructive',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Removes folder and unfiled contained cards in SQLite'],
      preconditions: ['Folder exists'],
      postconditions: ['Folder deleted', 'Contained cards unfiled'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
    'folder.moveFolder': {
      description: 'Move folder to new parent',
      parameters: { type: 'object', properties: { folderId: { type: 'string' }, newParentId: { type: 'string' } }, required: ['folderId', 'newParentId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists parent change to SQLite'],
      preconditions: ['Folder exists', 'New parent exists', 'No circular reference'],
      postconditions: ['Folder reparented'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND', 'CIRCULAR_REFERENCE'],
    },
    'folder.moveCard': {
      description: 'Move card into folder',
      parameters: { type: 'object', properties: { cardId: { type: 'string' }, folderId: { type: 'string' } }, required: ['cardId', 'folderId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Persists card-folder association to SQLite'],
      preconditions: ['Card exists', 'Folder exists'],
      postconditions: ['Card filed in folder'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
    'folder.unfileCard': {
      description: 'Remove card from folder',
      parameters: { type: 'object', properties: { cardId: { type: 'string' } }, required: ['cardId'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'folders:write' }],
      affected_stores: ['folders'],
      side_effects: ['Removes card-folder association from SQLite'],
      preconditions: ['Card is filed in a folder'],
      postconditions: ['Card unfiled'],
      idempotent: true,
      async: true,
      latency: 'fast',
      error_codes: ['NOT_FOUND'],
    },
  },
  actions: {
    toggleCollapse: { description: 'Expand or collapse a container node', trigger_command: 'internal', context_description: 'Local state: toggles container ID in collapsed set' },
    navigateContainer: { description: 'Navigate into a container', trigger_command: 'internal', context_description: 'Local state: sets active container for drill-down' },
  },
  events: {},
  context: [],
};

// ─── Implemented Architectural Components (M5) ─────────────────────────────

const PROMPT_BOX: ComponentDescription = {
  schema_version: 1,
  id: 'prompt_box',
  path: 'app.workspace.prompt_box',
  name: 'Prompt Box',
  description: 'Staged prompt input at the bottom of the workspace. Sends text to the active terminal session via Cmd+Enter. Per-session draft preservation across tab switches.',
  parent: 'workspace',
  children: [],
  state: {
    text: {
      schema: { type: 'string' },
      description: 'Current draft text for the active session',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: '',
    },
    minHeight: {
      schema: { type: 'number' },
      description: 'Minimum height of the textarea in pixels',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 60,
    },
  },
  commands: {
    'prompt.send': {
      description: 'Send staged text to the active terminal session',
      parameters: { type: 'object', properties: { sessionId: { type: 'string' }, text: { type: 'string' } } },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'sessions:write' }],
      affected_stores: [],
      side_effects: ['Writes text to terminal PTY'],
      preconditions: ['Session exists', 'Text is non-empty'],
      postconditions: ['Text delivered to terminal'],
      idempotent: false,
      async: true,
      latency: 'fast',
      error_codes: ['PROMPT_SEND_FAILED'],
    },
  },
  actions: {
    send: {
      description: 'Send prompt text to terminal',
      trigger_command: 'prompt.send',
      context_description: 'session ID and prompt text',
      shortcut: 'Cmd+Enter',
    },
  },
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Session the prompt targets', required: true },
  ],
};

const TERMINAL_PANE: ComponentDescription = {
  schema_version: 1,
  id: 'terminal_pane',
  path: 'app.workspace.session_pane.terminal_pane',
  name: 'Terminal Pane',
  description: 'xterm.js terminal attached to a tmux session via node-pty. Handles input forwarding, resize, selection overlay, and optional Memorex split view.',
  parent: 'session_pane',
  children: ['memorex_view'],
  state: {
    memorexEnabled: {
      schema: { type: 'boolean' },
      description: 'Whether the Memorex transcript overlay is visible',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: false,
    },
    memorexSplit: {
      schema: { type: 'number', minimum: 15, maximum: 85 },
      description: 'Memorex/terminal split percentage',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: 70,
    },
  },
  commands: {
    'prompt.send': {
      description: 'Send text to the terminal',
      parameters: { type: 'object', properties: { sessionId: { type: 'string' }, text: { type: 'string' } }, required: ['sessionId', 'text'] },
      returns: { type: 'object', properties: { ok: { type: 'boolean' } } },
      safety: 'safe',
      required_capabilities: [{ capability: 'terminal:send_staged' }],
      affected_stores: [],
      side_effects: ['Writes text to terminal PTY'],
      preconditions: ['Session exists', 'Terminal is attached'],
      postconditions: ['Text delivered to terminal'],
      idempotent: false,
      async: true,
      latency: 'fast',
      error_codes: ['PROMPT_SEND_FAILED', 'NOT_ATTACHED'],
    },
  },
  actions: {
    toggleMemorex: {
      description: 'Toggle Memorex transcript overlay',
      trigger_command: 'internal',
      context_description: 'Local state toggle for memorexEnabled',
    },
  },
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Session whose terminal is displayed', required: true },
  ],
};

const MEMOREX_VIEW: ComponentDescription = {
  schema_version: 1,
  id: 'memorex_view',
  path: 'app.workspace.session_pane.terminal_pane.memorex_view',
  name: 'Memorex View',
  description: 'Dual-zone terminal display rendering structured JSONL transcripts as collapsible message blocks with auto-refresh polling. Sanitizes markdown via DOMPurify.',
  parent: 'terminal_pane',
  children: [],
  state: {
    loading: {
      schema: { type: 'boolean' },
      description: 'Whether a transcript fetch is in progress',
      readable: true,
      writable: false,
      write_mechanism: 'local',
      default_value: false,
    },
    enabled: {
      schema: { type: 'boolean' },
      description: 'Whether the Memorex view is active',
      readable: true,
      writable: true,
      write_mechanism: 'local',
      default_value: false,
    },
  },
  commands: {},
  actions: {},
  events: {},
  context: [
    { key: 'entity_ref', type: 'EntityRef', description: 'Session whose transcript is displayed', required: true },
  ],
};

// ─── Registration ─────────────────────────────────────────────────────────

function makeDescribable(desc: ComponentDescription): DescribableComponent {
  return { describe: () => desc };
}

export function registerInitialComponents(): void {
  ComponentRegistry.register('app', makeDescribable(APP_ROOT));
  ComponentRegistry.register('session_navigator', makeDescribable(SESSION_NAVIGATOR));
  ComponentRegistry.register('workspace', makeDescribable(WORKSPACE));
  ComponentRegistry.register('entity_view', makeDescribable(ENTITY_VIEW));
  ComponentRegistry.register('session_pane', makeDescribable(SESSION_PANE));
  ComponentRegistry.register('context_panel', makeDescribable(CONTEXT_PANEL));
  ComponentRegistry.register('bottom_panel', makeDescribable(BOTTOM_PANEL));
  ComponentRegistry.register('card_list', makeDescribable(CARD_LIST_VIEW));
  ComponentRegistry.register('container_tree', makeDescribable(CONTAINER_TREE_VIEW));
  ComponentRegistry.register('prompt_box', makeDescribable(PROMPT_BOX));
  ComponentRegistry.register('terminal_pane', makeDescribable(TERMINAL_PANE));
  ComponentRegistry.register('memorex_view', makeDescribable(MEMOREX_VIEW));
}
